// <auto-generated />
namespace NGVSCAN.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedROC809MeasurePoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedROC809MeasurePoint));
        
        string IMigrationMetadata.Id
        {
            get { return "201605162050462_AddedROC809MeasurePoint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
